spring.application.name=Produto


# Banco H2 em memória com URL fixa
spring.datasource.url= jdbc:h2:mem:produtosdb
spring.datasource.username=sa
spring.datasource.password=

# Mostra o SQL no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Console web do H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
